name: Create and Upload JSON File

on:
  workflow_dispatch:

jobs:
  create-upload-json:
    runs-on: ubuntu-latest

    steps:
      - name: Create `discord.json` from secret
        run: |
          echo "${{ secrets.DISCORD_JSON }}" > discord.json

      - name: Upload `discord.json` as artifact
        uses: actions/upload-artifact@v4
        with:
          name: discord-config
          path: discord.json
