name: Create discord.json from Secret

on: [workflow_dispatch]  # Trigger manually

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Create discord.json from secret
        run: |
          echo "${{ secrets.test }}" > discord.json

      - name: Upload discord.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: discord-config
          path: discord.json
