name: Create JSON File from Secret

on:
  push:

jobs:
  create-discord-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write JSON to file
        run: |
          echo "${{ secrets.DISCORD_JSON }}" > discord.json

      - name: Print to verify
        run: |
          cat discord.json
